"""Basic statistical analysis for the hybrid processed alerts dataset."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

PROJECT_ROOT = Path(__file__).resolve().parents[1]
EVENTS_PATH = PROJECT_ROOT / "data" / "processed" / "alerts_merged_event_level.csv"
DAILY_PATH = PROJECT_ROOT / "data" / "processed" / "daily_oblast_timeseries.csv"
HOURLY_PATH = PROJECT_ROOT / "data" / "processed" / "hourly_oblast_timeseries.csv"
TABLES_DIR = PROJECT_ROOT / "outputs" / "tables"
FIGURES_DIR = PROJECT_ROOT / "outputs" / "figures"

OBLAST_SUMMARY_PATH = TABLES_DIR / "oblast_summary.csv"
SEASONALITY_SUMMARY_PATH = TABLES_DIR / "seasonality_summary.csv"

DAYS_OF_WEEK = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
]

OBLAST_ALIASES = {
    "crimea": "Crimea",
    "kyiv": "Kyiv City",
    "kyiv city": "Kyiv City",
    "kyiv oblast": "Kyivska oblast",
    "kyiv region": "Kyivska oblast",
    "kyivska": "Kyivska oblast",
    "lviv oblast": "Lvivska oblast",
    "lviv region": "Lvivska oblast",
    "odesa oblast": "Odeska oblast",
    "odesa region": "Odeska oblast",
    "odessa oblast": "Odeska oblast",
    "odessa region": "Odeska oblast",
    "kharkiv oblast": "Kharkivska oblast",
    "kharkiv region": "Kharkivska oblast",
    "dnipro oblast": "Dnipropetrovska oblast",
    "dnipropetrovsk oblast": "Dnipropetrovska oblast",
    "dnipropetrovska": "Dnipropetrovska oblast",
    "donetsk oblast": "Donetska oblast",
    "donetsk region": "Donetska oblast",
    "zaporizhzhia oblast": "Zaporizka oblast",
    "zaporizhia oblast": "Zaporizka oblast",
}


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")


@dataclass(frozen=True)
class AnalysisOutputs:
    """Paths and tables generated by an analysis run."""

    selected_oblast: str
    oblast_summary: pd.DataFrame
    seasonality_summary: pd.DataFrame
    figure_paths: list[Path]
    table_paths: list[Path]


def load_event_level_alerts(path: Path = EVENTS_PATH) -> pd.DataFrame:
    """Load event-level merged alerts and parse UTC timestamps."""

    if not path.exists():
        raise FileNotFoundError(
            f"Missing merged event-level alerts: {path}. Run src/merge_sources.py first."
        )

    dataframe = pd.read_csv(path)
    required = {
        "source_record_id",
        "data_source",
        "oblast_name",
        "location_type",
        "alert_type",
        "started_at_utc",
        "finished_at_utc",
        "duration_minutes",
    }
    missing = sorted(required - set(dataframe.columns))
    if missing:
        raise ValueError(f"Event-level alerts missing required columns: {missing}")

    dataframe["started_at_utc"] = pd.to_datetime(
        dataframe["started_at_utc"],
        errors="coerce",
        utc=True,
        format="mixed",
    )
    dataframe["finished_at_utc"] = pd.to_datetime(
        dataframe["finished_at_utc"],
        errors="coerce",
        utc=True,
        format="mixed",
    )
    dataframe["duration_minutes"] = pd.to_numeric(
        dataframe["duration_minutes"],
        errors="coerce",
    )
    return dataframe


def load_daily_timeseries(path: Path = DAILY_PATH) -> pd.DataFrame:
    """Load oblast-level daily time series."""

    if not path.exists():
        raise FileNotFoundError(
            f"Missing daily oblast time series: {path}. "
            "Run src/preprocess_timeseries.py first."
        )

    dataframe = pd.read_csv(path)
    required = {
        "date",
        "oblast_name",
        "alert_count",
        "total_alert_minutes",
        "average_alert_duration",
        "had_alert_binary",
        "github_records_count",
        "api_records_count",
    }
    missing = sorted(required - set(dataframe.columns))
    if missing:
        raise ValueError(f"Daily time series missing required columns: {missing}")

    dataframe["date"] = pd.to_datetime(dataframe["date"], errors="coerce")
    numeric_columns = [
        "alert_count",
        "total_alert_minutes",
        "average_alert_duration",
        "had_alert_binary",
        "github_records_count",
        "api_records_count",
    ]
    for column in numeric_columns:
        dataframe[column] = pd.to_numeric(dataframe[column], errors="coerce")
    return dataframe.dropna(subset=["date", "oblast_name"])


def load_hourly_timeseries(path: Path = HOURLY_PATH) -> pd.DataFrame | None:
    """Load hourly time series when available."""

    if not path.exists():
        return None

    dataframe = pd.read_csv(path)
    if "hour_start_utc" not in dataframe.columns:
        return None

    dataframe["hour_start_utc"] = pd.to_datetime(
        dataframe["hour_start_utc"],
        errors="coerce",
        utc=True,
        format="mixed",
    )
    return dataframe.dropna(subset=["hour_start_utc", "oblast_name"])


def generate_oblast_summary(
    events: pd.DataFrame,
    daily: pd.DataFrame,
) -> pd.DataFrame:
    """Generate summary statistics by oblast."""

    event_summary = (
        events.groupby("oblast_name", dropna=False)
        .agg(
            total_alerts=("source_record_id", "nunique"),
            average_alert_duration=("duration_minutes", "mean"),
            median_alert_duration=("duration_minutes", "median"),
            longest_alert=("duration_minutes", "max"),
        )
        .reset_index()
    )

    daily_summary = (
        daily.groupby("oblast_name", dropna=False)
        .agg(
            total_alert_minutes=("total_alert_minutes", "sum"),
            number_of_days_with_alert=(
                "had_alert_binary",
                lambda values: int((values > 0).sum()),
            ),
        )
        .reset_index()
    )

    summary = event_summary.merge(daily_summary, on="oblast_name", how="outer")
    summary["total_alert_hours"] = summary["total_alert_minutes"] / 60
    summary = summary[
        [
            "oblast_name",
            "total_alerts",
            "total_alert_minutes",
            "total_alert_hours",
            "average_alert_duration",
            "median_alert_duration",
            "longest_alert",
            "number_of_days_with_alert",
        ]
    ]
    return summary.sort_values("total_alert_hours", ascending=False)


def generate_time_series_statistics(daily: pd.DataFrame) -> pd.DataFrame:
    """Add 7-day and 30-day rolling averages to daily time series."""

    sorted_daily = daily.sort_values(["oblast_name", "date"]).copy()
    grouped = sorted_daily.groupby("oblast_name", group_keys=False)
    sorted_daily["alert_count_7d_rolling_avg"] = grouped["alert_count"].transform(
        lambda series: series.rolling(window=7, min_periods=1).mean()
    )
    sorted_daily["alert_count_30d_rolling_avg"] = grouped["alert_count"].transform(
        lambda series: series.rolling(window=30, min_periods=1).mean()
    )
    sorted_daily["alert_minutes_7d_rolling_avg"] = grouped[
        "total_alert_minutes"
    ].transform(lambda series: series.rolling(window=7, min_periods=1).mean())
    sorted_daily["alert_minutes_30d_rolling_avg"] = grouped[
        "total_alert_minutes"
    ].transform(lambda series: series.rolling(window=30, min_periods=1).mean())
    return sorted_daily


def generate_seasonality_summary(
    events: pd.DataFrame,
    daily: pd.DataFrame,
    hourly: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """Generate day-of-week, month, and optional hour-of-day seasonality stats."""

    day_of_week = daily.copy()
    day_of_week["seasonality_type"] = "day_of_week"
    day_of_week["seasonality_value"] = day_of_week["date"].dt.day_name()
    day_summary = aggregate_seasonality(day_of_week)
    day_summary["seasonality_order"] = day_summary["seasonality_value"].map(
        {name: index for index, name in enumerate(DAYS_OF_WEEK, start=1)}
    )

    month = daily.copy()
    month["seasonality_type"] = "month"
    month["seasonality_value"] = month["date"].dt.month_name()
    month_summary = aggregate_seasonality(month)
    month_summary["seasonality_order"] = pd.to_datetime(
        month_summary["seasonality_value"],
        format="%B",
        errors="coerce",
    ).dt.month

    summaries = [day_summary, month_summary]

    if hourly is not None and not hourly.empty:
        hour = hourly.copy()
        hour["seasonality_type"] = "hour_of_day_utc"
        hour["seasonality_value"] = hour["hour_start_utc"].dt.hour.astype("string")
        hour_summary = aggregate_seasonality(hour)
        hour_summary["seasonality_order"] = pd.to_numeric(
            hour_summary["seasonality_value"],
            errors="coerce",
        )
        summaries.append(hour_summary)

    return pd.concat(summaries, ignore_index=True).sort_values(
        ["oblast_name", "seasonality_type", "seasonality_order"]
    )


def aggregate_seasonality(dataframe: pd.DataFrame) -> pd.DataFrame:
    """Aggregate seasonality rows using shared output columns."""

    return (
        dataframe.groupby(
            ["oblast_name", "seasonality_type", "seasonality_value"],
            dropna=False,
        )
        .agg(
            alert_count=("alert_count", "sum"),
            total_alert_minutes=("total_alert_minutes", "sum"),
            average_alert_minutes=("total_alert_minutes", "mean"),
            days_or_hours_observed=("total_alert_minutes", "size"),
        )
        .reset_index()
    )


def save_summary_tables(
    oblast_summary: pd.DataFrame,
    seasonality_summary: pd.DataFrame,
    *,
    tables_dir: Path = TABLES_DIR,
) -> list[Path]:
    """Save summary CSV tables."""

    tables_dir.mkdir(parents=True, exist_ok=True)
    oblast_summary.to_csv(OBLAST_SUMMARY_PATH, index=False)
    seasonality_summary.to_csv(SEASONALITY_SUMMARY_PATH, index=False)
    return [OBLAST_SUMMARY_PATH, SEASONALITY_SUMMARY_PATH]


def generate_figures(
    *,
    selected_oblast: str,
    events: pd.DataFrame,
    oblast_summary: pd.DataFrame,
    daily_stats: pd.DataFrame,
    seasonality_summary: pd.DataFrame,
    figures_dir: Path = FIGURES_DIR,
) -> list[Path]:
    """Generate static Matplotlib/Seaborn figures."""

    figures_dir.mkdir(parents=True, exist_ok=True)
    sns.set_theme(style="whitegrid", context="notebook")

    paths = [
        plot_top_oblasts_by_hours(oblast_summary, figures_dir),
        plot_daily_alert_activity(selected_oblast, daily_stats, figures_dir),
        plot_rolling_average(selected_oblast, daily_stats, figures_dir),
        plot_day_of_week_pattern(selected_oblast, seasonality_summary, figures_dir),
        plot_monthly_pattern(selected_oblast, seasonality_summary, figures_dir),
        plot_duration_distribution(selected_oblast, events, figures_dir),
    ]
    return paths


def plot_top_oblasts_by_hours(summary: pd.DataFrame, figures_dir: Path) -> Path:
    path = figures_dir / "top_oblasts_by_total_alert_hours.png"
    top = summary.nlargest(12, "total_alert_hours").sort_values("total_alert_hours")

    fig, ax = plt.subplots(figsize=(10, 7))
    sns.barplot(
        data=top,
        x="total_alert_hours",
        y="oblast_name",
        color="#2563eb",
        ax=ax,
    )
    ax.set_title("Top oblasts by total alert hours")
    ax.set_xlabel("Total alert hours")
    ax.set_ylabel("")
    save_figure(fig, path)
    return path


def plot_daily_alert_activity(
    selected_oblast: str,
    daily_stats: pd.DataFrame,
    figures_dir: Path,
) -> Path:
    path = figures_dir / f"{slugify(selected_oblast)}_daily_alert_activity.png"
    selected = daily_stats[daily_stats["oblast_name"] == selected_oblast]

    fig, ax = plt.subplots(figsize=(12, 5))
    sns.lineplot(
        data=selected,
        x="date",
        y="total_alert_minutes",
        color="#2563eb",
        linewidth=1,
        ax=ax,
    )
    ax.set_title(f"Daily alert activity: {selected_oblast}")
    ax.set_xlabel("Date")
    ax.set_ylabel("Total alert minutes")
    fig.autofmt_xdate()
    save_figure(fig, path)
    return path


def plot_rolling_average(
    selected_oblast: str,
    daily_stats: pd.DataFrame,
    figures_dir: Path,
) -> Path:
    path = figures_dir / f"{slugify(selected_oblast)}_rolling_alert_count.png"
    selected = daily_stats[daily_stats["oblast_name"] == selected_oblast]

    fig, ax = plt.subplots(figsize=(12, 5))
    sns.lineplot(
        data=selected,
        x="date",
        y="alert_count_7d_rolling_avg",
        label="7-day rolling average",
        color="#dc2626",
        ax=ax,
    )
    sns.lineplot(
        data=selected,
        x="date",
        y="alert_count_30d_rolling_avg",
        label="30-day rolling average",
        color="#2563eb",
        ax=ax,
    )
    ax.set_title(f"Rolling average alert count: {selected_oblast}")
    ax.set_xlabel("Date")
    ax.set_ylabel("Alert count")
    fig.autofmt_xdate()
    save_figure(fig, path)
    return path


def plot_day_of_week_pattern(
    selected_oblast: str,
    seasonality: pd.DataFrame,
    figures_dir: Path,
) -> Path:
    path = figures_dir / f"{slugify(selected_oblast)}_day_of_week_pattern.png"
    selected = seasonality[
        (seasonality["oblast_name"] == selected_oblast)
        & (seasonality["seasonality_type"] == "day_of_week")
    ].copy()
    selected["seasonality_value"] = pd.Categorical(
        selected["seasonality_value"],
        categories=DAYS_OF_WEEK,
        ordered=True,
    )
    selected = selected.sort_values("seasonality_value")

    fig, ax = plt.subplots(figsize=(9, 5))
    sns.barplot(
        data=selected,
        x="seasonality_value",
        y="alert_count",
        color="#16a34a",
        ax=ax,
    )
    ax.set_title(f"Alert count by day of week: {selected_oblast}")
    ax.set_xlabel("")
    ax.set_ylabel("Alert count")
    ax.tick_params(axis="x", rotation=35)
    save_figure(fig, path)
    return path


def plot_monthly_pattern(
    selected_oblast: str,
    seasonality: pd.DataFrame,
    figures_dir: Path,
) -> Path:
    path = figures_dir / f"{slugify(selected_oblast)}_monthly_pattern.png"
    selected = seasonality[
        (seasonality["oblast_name"] == selected_oblast)
        & (seasonality["seasonality_type"] == "month")
    ].sort_values("seasonality_order")

    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(
        data=selected,
        x="seasonality_value",
        y="alert_count",
        color="#9333ea",
        ax=ax,
    )
    ax.set_title(f"Alert count by month: {selected_oblast}")
    ax.set_xlabel("")
    ax.set_ylabel("Alert count")
    ax.tick_params(axis="x", rotation=35)
    save_figure(fig, path)
    return path


def plot_duration_distribution(
    selected_oblast: str,
    events: pd.DataFrame,
    figures_dir: Path,
) -> Path:
    path = figures_dir / f"{slugify(selected_oblast)}_alert_duration_distribution.png"
    selected = events[
        (events["oblast_name"] == selected_oblast)
        & events["duration_minutes"].notna()
        & (events["duration_minutes"] >= 0)
    ].copy()
    cap = selected["duration_minutes"].quantile(0.99)
    selected = selected[selected["duration_minutes"] <= cap]

    fig, ax = plt.subplots(figsize=(10, 5))
    sns.histplot(
        data=selected,
        x="duration_minutes",
        bins=50,
        color="#ea580c",
        ax=ax,
    )
    ax.set_title(f"Alert duration distribution: {selected_oblast}")
    ax.set_xlabel("Duration minutes, capped at 99th percentile")
    ax.set_ylabel("Events")
    save_figure(fig, path)
    return path


def save_figure(fig: plt.Figure, path: Path) -> None:
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def resolve_oblast_name(requested: str, available: list[str]) -> str:
    """Resolve user-friendly oblast aliases to dataset names."""

    if requested in available:
        return requested

    normalized_requested = normalize_lookup(requested)
    alias = OBLAST_ALIASES.get(normalized_requested)
    if alias in available:
        return alias

    normalized_available = {normalize_lookup(name): name for name in available}
    if normalized_requested in normalized_available:
        return normalized_available[normalized_requested]

    stripped_requested = normalized_requested.replace(" oblast", "").replace(" region", "")
    for normalized_name, original_name in normalized_available.items():
        stripped_name = normalized_name.replace(" oblast", "").replace(" region", "")
        if stripped_requested == stripped_name:
            return original_name

    close = ", ".join(available[:12])
    raise ValueError(
        f"Unknown oblast {requested!r}. Available examples: {close}"
    )


def normalize_lookup(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().casefold())


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", value.strip().lower()).strip("_")
    return slug or "selected_oblast"


def run_analysis(
    *,
    oblast: str,
    events_path: Path = EVENTS_PATH,
    daily_path: Path = DAILY_PATH,
    hourly_path: Path = HOURLY_PATH,
) -> AnalysisOutputs:
    """Run the full basic statistical analysis layer."""

    events = load_event_level_alerts(events_path)
    daily = load_daily_timeseries(daily_path)
    hourly = load_hourly_timeseries(hourly_path)

    available_oblasts = sorted(daily["oblast_name"].dropna().unique().tolist())
    selected_oblast = resolve_oblast_name(oblast, available_oblasts)

    oblast_summary = generate_oblast_summary(events, daily)
    daily_stats = generate_time_series_statistics(daily)
    seasonality_summary = generate_seasonality_summary(events, daily, hourly)

    table_paths = save_summary_tables(oblast_summary, seasonality_summary)
    figure_paths = generate_figures(
        selected_oblast=selected_oblast,
        events=events,
        oblast_summary=oblast_summary,
        daily_stats=daily_stats,
        seasonality_summary=seasonality_summary,
    )

    return AnalysisOutputs(
        selected_oblast=selected_oblast,
        oblast_summary=oblast_summary,
        seasonality_summary=seasonality_summary,
        figure_paths=figure_paths,
        table_paths=table_paths,
    )


def print_analysis_summary(outputs: AnalysisOutputs) -> None:
    """Print a compact run summary for CLI use."""

    selected_summary = outputs.oblast_summary[
        outputs.oblast_summary["oblast_name"] == outputs.selected_oblast
    ]

    print("Basic statistical analysis complete")
    print(f"Selected oblast: {outputs.selected_oblast}")
    if not selected_summary.empty:
        print("\nSelected oblast summary")
        print(selected_summary.to_string(index=False))

    print("\nGenerated tables")
    for path in outputs.table_paths:
        print(f"- {path}")

    print("\nGenerated figures")
    for path in outputs.figure_paths:
        print(f"- {path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run basic statistical analysis for Ukrainian alert data."
    )
    parser.add_argument(
        "--oblast",
        required=True,
        help='Selected oblast for figures, e.g. "Kyiv Oblast" or "Kyiv City".',
    )
    return parser.parse_args()


def main(argv: list[str] | None = None) -> int:
    args = parse_args() if argv is None else parse_args_from(argv)
    outputs = run_analysis(oblast=args.oblast)
    print_analysis_summary(outputs)
    return 0


def parse_args_from(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run basic statistical analysis for Ukrainian alert data."
    )
    parser.add_argument("--oblast", required=True)
    return parser.parse_args(argv)


if __name__ == "__main__":
    raise SystemExit(main())
